[package]
name = "log_tracker_app"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.17.0"
mlua = { version = "0.8.8", features = ["lua54", "serialize"] }
serde = "1.0.156"
serde_json = "1.0.94"
graphql_client = "0.12.0"